// frontend/src/components/Navbar.jsx
import React, { useContext } from "react";
import { Link } from "react-router-dom";
import { Web3Context } from "../context/Web3Context";

const Navbar = () => {
  const { account, connectWallet, networkName } = useContext(Web3Context);

  return (
    <nav className="bg-white shadow-md">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between h-16">
          <div className="flex items-center">
            <Link to="/" className="text-2xl font-bold text-eco-green">
              GreenPulse
            </Link>
            <div className="hidden md:flex ml-10 space-x-8">
              <Link
                to="/"
                className="text-gray-700 hover:text-eco-dark px-3 py-2 rounded-md font-medium"
              >
                Campaigns
              </Link>
              <Link
                to="/create"
                className="text-gray-700 hover:text-eco-dark px-3 py-2 rounded-md font-medium"
              >
                Start Campaign
              </Link>
              <Link
                to="/profile"
                className="text-gray-700 hover:text-eco-dark px-3 py-2 rounded-md font-medium"
              >
                My Profile
              </Link>
            </div>
          </div>
          <div className="flex items-center">
            {account ? (
              <div className="flex items-center space-x-4">
                <span
                  className={`px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider ${
                    networkName === "Localhost" || networkName === "Sepolia"
                      ? "bg-green-100 text-green-800"
                      : "bg-red-100 text-red-800"
                  }`}
                >
                  {networkName || "Wrong Network"}
                </span>
                <span className="bg-eco-light text-eco-dark px-4 py-2 rounded-full font-mono text-sm">
                  {account.slice(0, 6)}...{account.slice(-4)}
                </span>
              </div>
            ) : (
              <button
                onClick={connectWallet}
                className="bg-eco-green text-white px-4 py-2 rounded-md font-medium hover:bg-eco-dark transition-colors"
                id="connect-wallet-btn"
              >
                Connect Wallet
              </button>
            )}
          </div>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;

// frontend/src/app/shared/components/navbar/navbar.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { Web3Service } from '../../../core/services/web3.service';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css'],
})
export class NavbarComponent {
  web3Service = inject(Web3Service);

  account = this.web3Service.account;
  tokenBalance = this.web3Service.tokenBalance;

  connect() {
    this.web3Service.connectWallet();
  }

  shortenAddress(address: string | null): string {
    if (!address) return ''; // Safely handle null
    return `${address.slice(0, 6)}...${address.slice(-4)}`;
  }
}

<nav
  class="block w-full max-w-screen-xl px-4 py-3 mx-auto text-white bg-slate-900 shadow-md rounded-xl border border-slate-800 my-4 sticky top-4 z-50"
>
  <div class="flex flex-wrap items-center justify-between text-slate-100 gap-y-4">
    <a
      routerLink="/"
      class="mr-4 block cursor-pointer py-1.5 font-sans text-base font-semibold leading-relaxed tracking-normal text-inherit antialiased hover:text-emerald-400 transition-colors"
    >
      GreenPulse
    </a>
    <div class="flex gap-2">
      <a
        routerLink="/"
        routerLinkActive="text-emerald-400"
        [routerLinkActiveOptions]="{ exact: true }"
        class="hidden lg:inline-block"
      >
        <button
          class="select-none rounded-lg px-4 py-2 text-center align-middle font-sans text-xs font-bold uppercase text-slate-100 transition-all hover:bg-slate-800 active:bg-slate-800 disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none"
          type="button"
        >
          Home
        </button>
      </a>
      <a routerLink="/create" routerLinkActive="text-emerald-400">
        <button
          class="select-none rounded-lg px-4 py-2 text-center align-middle font-sans text-xs font-bold uppercase text-slate-100 transition-all hover:bg-slate-800 active:bg-slate-800 disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none"
          type="button"
        >
          Create Campaign
        </button>
      </a>
      <a routerLink="/profile" routerLinkActive="text-emerald-400">
        <button
          class="select-none rounded-lg px-4 py-2 text-center align-middle font-sans text-xs font-bold uppercase text-slate-100 transition-all hover:bg-slate-800 active:bg-slate-800 disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none"
          type="button"
        >
          Profile
        </button>
      </a>
    </div>
    <div class="relative flex w-full gap-2 md:w-max">
      <button
        (click)="connect()"
        class="flex items-center gap-1.5 align-middle select-none font-sans font-bold text-center uppercase transition-all disabled:opacity-50 disabled:shadow-none disabled:pointer-events-none text-xs py-2 px-4 rounded-lg bg-emerald-500 text-white shadow-md shadow-emerald-500/20 hover:shadow-lg hover:shadow-emerald-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none"
        type="button"
      >
        <span
          *ngIf="account()"
          class="text-white/90 font-mono text-[10px] bg-white/10 px-2 py-0.5 rounded border border-white/20 mr-1"
        >
          {{ tokenBalance() | number : '1.0-2' }} LEAF
        </span>
        {{ account() ? shortenAddress(account()) : 'Connect Wallet' }}
      </button>
    </div>
  </div>
</nav>
